import type {Metadata} from "next";
import "./globals.css";
import {cn} from "@/app/_lib/utils";
import {Inter as FontSans} from "next/font/google"
import {ThemeProvider} from "next-themes";
import {createClient} from "@/app/_utils/supabase/server";
import {UserProvider} from "@/app/_context/UserContext";
import {Toaster} from "@/app/_components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: { children: React.ReactNode; }) {
    const supabase = createClient();
    const {data: {user}, error} = await supabase.auth.getUser();

    // Just to see activity in development.
    if (error || !user) {
        console.error('❌ [app/layout.tsx] NO user authenticated');
    }
    if (user) console.log('⭐️ [app/layout.tsx] user IS authenticated')

    return (
        <html lang="en" suppressHydrationWarning>
        <body className={cn("min-h-screen bg-background font-sans antialiased max-w-full", fontSans.variable)}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <UserProvider initialUser={user}>
                <NextTopLoader showSpinner={false} color={'hsl(var(--primary))'} easing={'ease'}/>
                {children}
            </UserProvider>
            <Toaster richColors closeButton position={'top-center'} />
        </ThemeProvider>
        </body>
        </html>
    );
}
