import type {Metadata} from "next";
import React from "react";
import '../globals.css';
import {Inter as FontSans} from "next/font/google";
import SideBar from "@/app/_components/SideBar";
import MobileNav from "@/app/_components/MobileNav";
import AdminSearch from "@/app/_components/AdminSearch";
import {ThemeToggle} from "@/app/_components/ThemeToggle";
import SiteTitle from "@/app/_components/SiteTitle";
import {createClient} from "@/app/_utils/supabase/server";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function DashLayout({children}: { children: React.ReactNode; }) {
    const supabase = createClient();
    const {data: {user}, error} = await supabase.auth.getUser();

    return (
        <div className="grid min-h-screen w-full md:grid-cols-[240px_1fr] lg:grid-cols-[280px_1fr]">
            <SideBar user={user}/>
            <div className="flex flex-col">
                <header
                    className="flex h-14 items-center gap-4 justify-between border-b bg-muted/40 px-4 lg:h-[60px] lg:px-6"
                >
                    <SiteTitle title={'Site Name'} />

                    <div className="w-full hidden md:flex">
                        <div className={'w-full'}>
                            {/*<AdminSearch/>*/}
                        </div>
                        <div className={'ml-auto'}>
                            <ThemeToggle />
                        </div>
                    </div>
                    <MobileNav user={user}/>
                </header>
                <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
                    {children}
                </main>
            </div>
        </div>
    );
}
